language: php
php:
    - '5.3'
script:
    - vendor/bin/phpunit --bootstrap garp/tests/TestHelper.php tests/
    # @todo: Probably the memlimit param can be taken off - had to do with db error
    - php -d memory_limit=-1 vendor/bin/phpunit --bootstrap garp/tests/TestHelper.php garp/tests/
before_install:
    #- gem install semver
    #- rm -rf node_modules
    #- npm install -g gulp
    #- npm install node-sass
    #- npm install gulp-sass
    #- npm install
    #- git clone https://github.com/grrr-amsterdam/golem ../golem
    - mysql -e "create database IF NOT EXISTS garpscaffold_t;" -uroot
    - mysql -e "create user garp_development@localhost identified by 'welovegarp';" -uroot
    - mysql -e "grant all privileges on *.* to garp_development@localhost;" -uroot
    - php garp/scripts/garp.php spawn -b --e=testing
before_script:
    - chmod -R +x vendor
    #- gulp --dev
notifications:
    email: false
    slack:
        secure: h9R+NUBeVXZfJ37cbdX72/ICIYS8mXMS2WR8DGDsTCx+mT6cru+D1UvnorXpOcPkv8FdX6aDHfK8LjsAT1a3IgcImRwVW4kdC7hq4L/NNlNNnTTchE/5+N6JqNY9nxrNweivMu/yuG/UzMVPLu5F1pyP3D26WGBelS3Y4eV+SgU=
