language: php
php:
    - '5.3'
script:
    - vendor/bin/phpunit --bootstrap garp/tests/TestHelper.php tests/
    # @todo: Probably the memlimit param can be taken off - had to do with db error
    - php -d memory_limit=-1 vendor/bin/phpunit --bootstrap garp/tests/TestHelper.php garp/tests/
before_install:
    #- gem install semver
    #- rm -rf node_modules
    #- npm install -g gulp
    #- npm install node-sass
    #- npm install gulp-sass
    #- npm install
    #- git clone https://github.com/grrr-amsterdam/golem ../golem
    - mysql -e "create database IF NOT EXISTS garpscaffold_t;" -uroot
    - mysql -e "create user garp_development@localhost identified by 'welovegarp';" -uroot
    - mysql -e "grant all privileges on *.* to garp_development@localhost;" -uroot
    - php garp/scripts/garp.php spawn -b --e=testing
    - composer install
before_script:
    #- chmod -R +x vendor
    #- gulp --dev

    # Set MySQL timezone for Melkweg db unit tests
    #- echo 'Europe/Amsterdam' | sudo tee /etc/timezone
    #- sudo dpkg-reconfigure --frontend noninteractive tzdata
    #- sudo service mysql restart
notifications:
    email: false
    slack:
        rooms:
            - secure: h9R+NUBeVXZfJ37cbdX72/ICIYS8mXMS2WR8DGDsTCx+mT6cru+D1UvnorXpOcPkv8FdX6aDHfK8LjsAT1a3IgcImRwVW4kdC7hq4L/NNlNNnTTchE/5+N6JqNY9nxrNweivMu/yuG/UzMVPLu5F1pyP3D26WGBelS3Y4eV+SgU=
        on_success: change
        on_failure: always
        template: "<%{build_url}|%{repository_name} [%{branch}] #%{build_number}>:\n%{message} (in %{duration})\nBy: %{author}\n<%{compare_url}|%{commit_message}>"
