language: php
php:
- '5.3'
script:
- phpunit --bootstrap garp/tests/TestHelper.php tests/
#- phpunit --bootstrap garp/tests/TestHelper.php garp/tests/
notifications:
  slack:
    secure: h9R+NUBeVXZfJ37cbdX72/ICIYS8mXMS2WR8DGDsTCx+mT6cru+D1UvnorXpOcPkv8FdX6aDHfK8LjsAT1a3IgcImRwVW4kdC7hq4L/NNlNNnTTchE/5+N6JqNY9nxrNweivMu/yuG/UzMVPLu5F1pyP3D26WGBelS3Y4eV+SgU=
