language: php

php:
  - "5.4"
  - "5.3

script: phpunit --verbose --colors --bootstrap garp/tests/TestHelper.php tests/
script: phpunit --verbose --colors --bootstrap garp/tests/TestHelper.php garp/tests/
